//! Smoke tests for the generic / ANSI DDL emitter.
//!
//! Step 1 covers structural correctness only — every `TableChange`
//! variant must produce at least one statement and the output must
//! qualify table names. The engine-specific emitters in Step 2 will
//! ship round-trip tests against live databases.

use narwhal_core::schema::{Column, Table, TableKind, TableSchema};
use narwhal_schema_diff::emit::{DdlEmitter, GenericEmitter, emitter_by_name};
use narwhal_schema_diff::{ColumnChange, SchemaDiff, TableChange, diff};

fn col(name: &str, ty: &str) -> Column {
    Column {
        name: name.into(),
        data_type: ty.into(),
        nullable: true,
        primary_key: false,
        default: None,
    }
}

fn table(name: &str, cols: Vec<Column>) -> TableSchema {
    TableSchema {
        table: Table {
            schema: "public".into(),
            name: name.into(),
            kind: TableKind::Table,
        },
        columns: cols,
        indexes: Vec::new(),
        foreign_keys: Vec::new(),
        unique_constraints: Vec::new(),
    }
}

#[test]
fn create_table_added() {
    let source = vec![table(
        "users",
        vec![col("id", "int4"), col("email", "text")],
    )];
    let d = diff(&source, &[]);
    let sql = GenericEmitter::new().emit(&d).unwrap();
    assert!(sql.contains("CREATE TABLE public.users"));
    assert!(sql.contains("id int4"));
    assert!(sql.contains("email text"));
}

#[test]
fn drop_table_removed() {
    let target = vec![table("legacy", vec![col("id", "int4")])];
    let d = diff(&[], &target);
    let sql = GenericEmitter::new().emit(&d).unwrap();
    assert!(sql.contains("DROP TABLE public.legacy"));
}

#[test]
fn add_column_alter() {
    let source = vec![table("u", vec![col("id", "int4"), col("email", "text")])];
    let target = vec![table("u", vec![col("id", "int4")])];
    let d = diff(&source, &target);
    let sql = GenericEmitter::new().emit(&d).unwrap();
    assert!(
        sql.contains("ALTER TABLE public.u ADD COLUMN email text"),
        "got:\n{sql}"
    );
}

#[test]
fn drop_column_alter() {
    let source = vec![table("u", vec![col("id", "int4")])];
    let target = vec![table("u", vec![col("id", "int4"), col("legacy", "text")])];
    let d = diff(&source, &target);
    let sql = GenericEmitter::new().emit(&d).unwrap();
    assert!(
        sql.contains("ALTER TABLE public.u DROP COLUMN legacy"),
        "got:\n{sql}"
    );
}

#[test]
fn nullable_drop_not_null() {
    let mut source_col = col("c", "int4");
    let target_col = {
        let mut c = col("c", "int4");
        c.nullable = false;
        c
    };
    source_col.nullable = true;
    let source = vec![table("u", vec![source_col])];
    let target = vec![table("u", vec![target_col])];
    let d = diff(&source, &target);
    let sql = GenericEmitter::new().emit(&d).unwrap();
    assert!(
        sql.contains("DROP NOT NULL"),
        "should drop NOT NULL when source is nullable; got:\n{sql}"
    );
}

#[test]
fn nullable_set_not_null() {
    let source_col = {
        let mut c = col("c", "int4");
        c.nullable = false;
        c
    };
    let target = vec![table("u", vec![col("c", "int4")])];
    let source = vec![table("u", vec![source_col])];
    let d = diff(&source, &target);
    let sql = GenericEmitter::new().emit(&d).unwrap();
    assert!(sql.contains("SET NOT NULL"), "got:\n{sql}");
}

#[test]
fn default_drop_and_set() {
    let with_default = {
        let mut c = col("c", "int4");
        c.default = Some("0".into());
        c
    };
    // SET DEFAULT path
    let d_set = diff(
        &[table("u", vec![with_default.clone()])],
        &[table("u", vec![col("c", "int4")])],
    );
    let sql_set = GenericEmitter::new().emit(&d_set).unwrap();
    assert!(sql_set.contains("SET DEFAULT 0"), "got:\n{sql_set}");

    // DROP DEFAULT path
    let d_drop = diff(
        &[table("u", vec![col("c", "int4")])],
        &[table("u", vec![with_default])],
    );
    let sql_drop = GenericEmitter::new().emit(&d_drop).unwrap();
    assert!(sql_drop.contains("DROP DEFAULT"), "got:\n{sql_drop}");
}

#[test]
fn empty_diff_emits_only_header() {
    let sql = GenericEmitter::new().emit(&SchemaDiff::default()).unwrap();
    assert!(sql.starts_with("-- generated by narwhal schema-diff"));
    // No DDL lines — only the header.
    let lines: Vec<&str> = sql.lines().filter(|l| !l.starts_with("--")).collect();
    assert!(lines.iter().all(|l| l.trim().is_empty()), "got:\n{sql}");
}

#[test]
fn type_change_emits_todo_comment() {
    let source = vec![table("u", vec![col("c", "int8")])];
    let target = vec![table("u", vec![col("c", "int4")])];
    let d = diff(&source, &target);
    let sql = GenericEmitter::new().emit(&d).unwrap();
    // The generic emitter cannot pick the right `USING` clause; it
    // emits the intent as a TODO comment so the operator sees it
    // instead of running a half-broken statement.
    assert!(
        sql.contains("-- TODO: change type of public.u.c"),
        "got:\n{sql}"
    );
}

#[test]
fn emitter_lookup_returns_generic_for_known_aliases() {
    assert!(emitter_by_name("generic").is_some());
    assert!(emitter_by_name("ANSI").is_some());
    assert!(emitter_by_name("sql").is_some());
    assert!(emitter_by_name("unknown-dialect").is_none());
}

#[test]
fn emitter_name_is_stable() {
    assert_eq!(GenericEmitter::new().name(), "generic");
}

#[test]
fn changed_table_keeps_each_change_on_its_own_line() {
    // Every change is one statement on its own line so the TUI's
    // line-by-line preview keeps a 1:1 mapping with the diff tree.
    let source = vec![{
        let mut c1 = col("a", "int4");
        c1.nullable = false;
        let mut c2 = col("b", "text");
        c2.default = Some("'x'".into());
        table("u", vec![c1, c2])
    }];
    let target = vec![table("u", vec![col("a", "int4"), col("b", "text")])];
    let d = diff(&source, &target);
    let sql = GenericEmitter::new().emit(&d).unwrap();
    // SET NOT NULL on `a` and SET DEFAULT on `b` must be separate
    // statements; the generic emitter does not coalesce.
    let stmt_count = sql.matches("ALTER TABLE").count();
    assert_eq!(stmt_count, 2, "got:\n{sql}");
    // Each column change is reflected.
    let TableChange::Changed { columns, .. } = &d.tables[0] else {
        panic!();
    };
    assert!(
        columns
            .iter()
            .any(|c| matches!(c, ColumnChange::NullableChanged { .. }))
    );
    assert!(
        columns
            .iter()
            .any(|c| matches!(c, ColumnChange::DefaultChanged { .. }))
    );
}
