//! ANSI / generic fallback DDL emitter.
//!
//! Targets the lowest common denominator: `CREATE TABLE`, `DROP TABLE`,
//! `ALTER TABLE ... ADD COLUMN`, and `ALTER TABLE ... DROP COLUMN`.
//! Anything richer (`ALTER COLUMN TYPE`, `ALTER COLUMN SET NULL`,
//! recreating indexes) is emitted as a leading `-- TODO:` comment so
//! the operator sees the intent and can hand-craft the engine-specific
//! statement.
//!
//! Step 2 of T2-T2-C replaces this with engine-aware emitters; the
//! generic dialect stays as a safety net for engines without first
//! -party support and as a regression target for the integration
//! tests.

use crate::SchemaDiffError;
use crate::diff::{
    ColumnChange, ForeignKeyChange, IndexChange, SchemaDiff, TableChange, UniqueConstraintChange,
};
use narwhal_core::schema::{Column, TableSchema};

use super::{DdlEmitter, qualify};

/// ANSI / generic SQL emitter. Stateless.
#[derive(Debug, Default, Clone, Copy)]
pub struct GenericEmitter;

impl GenericEmitter {
    /// Construct a fresh emitter. Cheap; the type is zero-sized.
    #[must_use]
    pub const fn new() -> Self {
        Self
    }
}

impl DdlEmitter for GenericEmitter {
    fn name(&self) -> &'static str {
        "generic"
    }

    fn emit(&self, diff: &SchemaDiff) -> Result<String, SchemaDiffError> {
        // Pre-allocate roughly 128 bytes per change — the typical
        // ALTER is well under that and the heap doesn't mind being
        // generous when we're already in a one-shot tool.
        let mut out = String::with_capacity(diff.change_count() * 128 + 64);
        out.push_str("-- generated by narwhal schema-diff (generic dialect)\n");
        for table in &diff.tables {
            emit_one_table(&mut out, table);
            out.push('\n');
        }
        Ok(out)
    }
}

fn emit_one_table(out: &mut String, change: &TableChange) {
    match change {
        TableChange::Added(t) => emit_create_table(out, t),
        TableChange::Removed(t) => emit_drop_table(out, t),
        TableChange::Changed {
            table,
            columns,
            indexes,
            foreign_keys,
            unique_constraints,
        } => {
            let qualified = qualify(&table.schema, &table.name);
            for c in columns {
                emit_column_change(out, &qualified, c);
            }
            for i in indexes {
                emit_index_change(out, &qualified, i);
            }
            for f in foreign_keys {
                emit_fk_change(out, &qualified, f);
            }
            for u in unique_constraints {
                emit_unique_change(out, &qualified, u);
            }
        }
    }
}

fn emit_create_table(out: &mut String, schema: &TableSchema) {
    out.push_str("CREATE TABLE ");
    out.push_str(&qualify(&schema.table.schema, &schema.table.name));
    out.push_str(" (\n");
    for (i, c) in schema.columns.iter().enumerate() {
        out.push_str("    ");
        emit_column_def(out, c);
        if i + 1 < schema.columns.len() {
            out.push(',');
        }
        out.push('\n');
    }
    out.push_str(");\n");
    // Indexes + FKs + unique constraints follow as separate
    // statements. Even ANSI engines accept this shape; an inline
    // CONSTRAINT clause is dialect-flavoured enough to defer to the
    // real emitters.
    for idx in &schema.indexes {
        if idx.primary {
            continue;
        }
        emit_create_index(out, &schema.table.schema, &schema.table.name, idx);
    }
    for u in &schema.unique_constraints {
        let qualified = qualify(&schema.table.schema, &schema.table.name);
        out.push_str("ALTER TABLE ");
        out.push_str(&qualified);
        out.push_str(" ADD CONSTRAINT ");
        out.push_str(&u.name);
        out.push_str(" UNIQUE (");
        out.push_str(&u.columns.join(", "));
        out.push_str(");\n");
    }
    for f in &schema.foreign_keys {
        emit_fk_add(out, &qualify(&schema.table.schema, &schema.table.name), f);
    }
}

fn emit_drop_table(out: &mut String, schema: &TableSchema) {
    out.push_str("DROP TABLE ");
    out.push_str(&qualify(&schema.table.schema, &schema.table.name));
    out.push_str(";\n");
}

fn emit_column_def(out: &mut String, c: &Column) {
    out.push_str(&c.name);
    out.push(' ');
    out.push_str(&c.data_type);
    if !c.nullable {
        out.push_str(" NOT NULL");
    }
    if let Some(def) = c.default.as_ref() {
        out.push_str(" DEFAULT ");
        out.push_str(def);
    }
    if c.primary_key {
        out.push_str(" PRIMARY KEY");
    }
}

fn emit_column_change(out: &mut String, table: &str, change: &ColumnChange) {
    match change {
        ColumnChange::Added(c) => {
            out.push_str("ALTER TABLE ");
            out.push_str(table);
            out.push_str(" ADD COLUMN ");
            emit_column_def(out, c);
            out.push_str(";\n");
        }
        ColumnChange::Removed(c) => {
            out.push_str("ALTER TABLE ");
            out.push_str(table);
            out.push_str(" DROP COLUMN ");
            out.push_str(&c.name);
            out.push_str(";\n");
        }
        ColumnChange::TypeChanged {
            name,
            source,
            target,
        } => {
            // ANSI's `ALTER COLUMN ... TYPE` is supported but the
            // `USING` clause needed for non-trivial casts is
            // Postgres-only. Surface the intent and let the operator
            // pick the right form.
            out.push_str("-- TODO: change type of ");
            out.push_str(table);
            out.push('.');
            out.push_str(name);
            out.push_str(" (was ");
            out.push_str(target);
            out.push_str(", desired ");
            out.push_str(source);
            out.push_str(")\n");
        }
        ColumnChange::NullableChanged { name, source, .. } => {
            out.push_str("ALTER TABLE ");
            out.push_str(table);
            out.push_str(" ALTER COLUMN ");
            out.push_str(name);
            out.push_str(if *source {
                " DROP NOT NULL"
            } else {
                " SET NOT NULL"
            });
            out.push_str(";\n");
        }
        ColumnChange::DefaultChanged { name, source, .. } => {
            out.push_str("ALTER TABLE ");
            out.push_str(table);
            out.push_str(" ALTER COLUMN ");
            out.push_str(name);
            match source {
                Some(def) => {
                    out.push_str(" SET DEFAULT ");
                    out.push_str(def);
                }
                None => out.push_str(" DROP DEFAULT"),
            }
            out.push_str(";\n");
        }
    }
}

fn emit_index_change(out: &mut String, table: &str, change: &IndexChange) {
    match change {
        IndexChange::Added(idx) => {
            // We don't have the (schema, table) split here; the
            // caller already qualified the table string, so we
            // re-derive the schema-less form for the new index. The
            // generic emitter is best-effort — engines that need a
            // schema-qualified index name will be handled by the
            // dialect-specific emitters in step 2.
            out.push_str(&render_create_index(table, idx));
        }
        IndexChange::Removed(idx) => {
            out.push_str("DROP INDEX ");
            out.push_str(&idx.name);
            out.push_str(";\n");
        }
        IndexChange::Changed { source, target } => {
            out.push_str("DROP INDEX ");
            out.push_str(&target.name);
            out.push_str(";\n");
            out.push_str(&render_create_index(table, source));
        }
    }
}

fn emit_create_index(
    out: &mut String,
    _schema: &str,
    _table: &str,
    idx: &narwhal_core::schema::Index,
) {
    // Step-1 simplification: the qualified table identifier is built
    // by the caller for ALTER paths. For CREATE-TABLE follow-on
    // indexes we use the unqualified name; SQLite and SQLite-likes
    // accept that, and dialect emitters will rebuild this in step 2.
    out.push_str(&render_create_index("", idx));
}

fn render_create_index(table: &str, idx: &narwhal_core::schema::Index) -> String {
    let mut s = String::new();
    s.push_str("CREATE ");
    if idx.unique {
        s.push_str("UNIQUE ");
    }
    s.push_str("INDEX ");
    s.push_str(&idx.name);
    if !table.is_empty() {
        s.push_str(" ON ");
        s.push_str(table);
    }
    s.push_str(" (");
    s.push_str(&idx.columns.join(", "));
    s.push_str(");\n");
    s
}

fn emit_fk_change(out: &mut String, table: &str, change: &ForeignKeyChange) {
    match change {
        ForeignKeyChange::Added(f) => emit_fk_add(out, table, f),
        ForeignKeyChange::Removed(f) => emit_fk_drop(out, table, f),
        ForeignKeyChange::Changed { source, target } => {
            // Drop the old one before recreating with the new shape
            // so the alter is atomic at the constraint level. The
            // engine-specific emitters can refine this with
            // transactions.
            emit_fk_drop(out, table, target);
            emit_fk_add(out, table, source);
        }
    }
}

fn emit_fk_add(out: &mut String, table: &str, f: &narwhal_core::schema::ForeignKey) {
    out.push_str("ALTER TABLE ");
    out.push_str(table);
    out.push_str(" ADD CONSTRAINT ");
    out.push_str(&f.name);
    out.push_str(" FOREIGN KEY (");
    out.push_str(&f.columns.join(", "));
    out.push_str(") REFERENCES ");
    if let Some(s) = f.referenced_schema.as_deref() {
        out.push_str(s);
        out.push('.');
    }
    out.push_str(&f.referenced_table);
    out.push_str(" (");
    out.push_str(&f.referenced_columns.join(", "));
    out.push(')');
    if let Some(action) = f.on_update {
        out.push_str(" ON UPDATE ");
        out.push_str(action.as_sql());
    }
    if let Some(action) = f.on_delete {
        out.push_str(" ON DELETE ");
        out.push_str(action.as_sql());
    }
    out.push_str(";\n");
}

fn emit_fk_drop(out: &mut String, table: &str, f: &narwhal_core::schema::ForeignKey) {
    out.push_str("ALTER TABLE ");
    out.push_str(table);
    out.push_str(" DROP CONSTRAINT ");
    out.push_str(&f.name);
    out.push_str(";\n");
}

fn emit_unique_change(out: &mut String, table: &str, change: &UniqueConstraintChange) {
    match change {
        UniqueConstraintChange::Added(u) => {
            out.push_str("ALTER TABLE ");
            out.push_str(table);
            out.push_str(" ADD CONSTRAINT ");
            out.push_str(&u.name);
            out.push_str(" UNIQUE (");
            out.push_str(&u.columns.join(", "));
            out.push_str(");\n");
        }
        UniqueConstraintChange::Removed(u) => {
            out.push_str("ALTER TABLE ");
            out.push_str(table);
            out.push_str(" DROP CONSTRAINT ");
            out.push_str(&u.name);
            out.push_str(";\n");
        }
        UniqueConstraintChange::Changed { source, target } => {
            out.push_str("ALTER TABLE ");
            out.push_str(table);
            out.push_str(" DROP CONSTRAINT ");
            out.push_str(&target.name);
            out.push_str(";\n");
            out.push_str("ALTER TABLE ");
            out.push_str(table);
            out.push_str(" ADD CONSTRAINT ");
            out.push_str(&source.name);
            out.push_str(" UNIQUE (");
            out.push_str(&source.columns.join(", "));
            out.push_str(");\n");
        }
    }
}
