//! Microsoft `SQL Server` (T-SQL) DDL emitter.
//!
//! Targets `SQL Server` 2016+ and Azure `SQL`. Key engine quirks
//! relative to Postgres / `MySQL`:
//!
//! - **Defaults are first-class constraints.** `ALTER COLUMN ...
//!   SET DEFAULT` is *not* valid T-SQL; defaults are added via
//!   `ALTER TABLE ... ADD CONSTRAINT df_<table>_<col> DEFAULT (...)
//!   FOR <col>` and dropped via `ALTER TABLE ... DROP CONSTRAINT
//!   df_<table>_<col>`. The diff doesn't carry the existing default-
//!   constraint name (drivers seldom surface it), so we synthesise a
//!   deterministic name and emit a leading note explaining what to
//!   adjust if the engine reports a different one.
//! - **`ALTER COLUMN` rewrites the whole shape.** Like `MySQL`'s
//!   `MODIFY COLUMN`, T-SQL's `ALTER COLUMN` carries type + null in
//!   one statement; we therefore coalesce per-column deltas the way
//!   the `MySQL` emitter does.
//! - **Indexes are dropped with `DROP INDEX <name> ON <table>`.**
//! - **Schema separator is `.`**, identical to Postgres.

use std::collections::BTreeMap;

use narwhal_core::schema::{Column, ForeignKey, Index, TableSchema, UniqueConstraint};

use super::{DdlEmitter, qualify};
use crate::SchemaDiffError;
use crate::diff::{
    ColumnChange, ForeignKeyChange, IndexChange, SchemaDiff, TableChange, UniqueConstraintChange,
};

/// `SQL Server` / Azure `SQL` DDL emitter. Stateless.
#[derive(Debug, Default, Clone, Copy)]
pub struct MssqlEmitter;

impl MssqlEmitter {
    /// Construct a fresh emitter. Zero-cost.
    #[must_use]
    pub const fn new() -> Self {
        Self
    }
}

impl DdlEmitter for MssqlEmitter {
    fn name(&self) -> &'static str {
        "mssql"
    }

    fn emit(&self, diff: &SchemaDiff) -> Result<String, SchemaDiffError> {
        let mut out = String::with_capacity(diff.change_count() * 200 + 192);
        out.push_str("-- generated by narwhal schema-diff (mssql / sqlserver dialect)\n");
        out.push_str(
            "-- note: DEFAULT constraints are named `df_<table>_<column>` by\n\
             --       convention. If the engine assigned a different name (which\n\
             --       SQL Server does when no explicit name was given at table\n\
             --       creation) replace the synthesised name in the corresponding\n\
             --       DROP CONSTRAINT line.\n",
        );
        for change in &diff.tables {
            match change {
                TableChange::Added(t) => emit_create_table(&mut out, t),
                TableChange::Removed(t) => emit_drop_table(&mut out, t),
                TableChange::Changed {
                    table,
                    columns,
                    indexes,
                    foreign_keys,
                    unique_constraints,
                } => {
                    let qualified = qualify(&table.schema, &table.name);
                    emit_changed_table(
                        &mut out,
                        &table.name,
                        &qualified,
                        columns,
                        indexes,
                        foreign_keys,
                        unique_constraints,
                    );
                }
            }
            out.push('\n');
        }
        Ok(out)
    }
}

fn emit_create_table(out: &mut String, schema: &TableSchema) {
    out.push_str("CREATE TABLE ");
    out.push_str(&qualify(&schema.table.schema, &schema.table.name));
    out.push_str(" (\n");
    let total = schema.columns.len();
    for (i, c) in schema.columns.iter().enumerate() {
        out.push_str("    ");
        emit_column_def(out, &schema.table.name, c);
        if i + 1 < total {
            out.push(',');
        }
        out.push('\n');
    }
    out.push_str(");\n");
    let qualified = qualify(&schema.table.schema, &schema.table.name);
    for idx in &schema.indexes {
        if idx.primary {
            continue;
        }
        emit_create_index(out, &qualified, idx);
    }
    for u in &schema.unique_constraints {
        emit_add_unique(out, &qualified, u);
    }
    for f in &schema.foreign_keys {
        emit_add_fk(out, &qualified, f);
    }
}

fn emit_drop_table(out: &mut String, schema: &TableSchema) {
    out.push_str("DROP TABLE ");
    out.push_str(&qualify(&schema.table.schema, &schema.table.name));
    out.push_str(";\n");
}

fn emit_changed_table(
    out: &mut String,
    table_name: &str,
    qualified: &str,
    columns: &[ColumnChange],
    indexes: &[IndexChange],
    foreign_keys: &[ForeignKeyChange],
    unique_constraints: &[UniqueConstraintChange],
) {
    // Drop phase: FKs and UNIQUE first, indexes last. T-SQL refuses
    // to alter a column under a referencing constraint.
    for f in foreign_keys {
        match f {
            ForeignKeyChange::Removed(fk) => emit_drop_constraint(out, qualified, &fk.name),
            ForeignKeyChange::Changed { target, .. } => {
                emit_drop_constraint(out, qualified, &target.name);
            }
            ForeignKeyChange::Added(_) => {}
        }
    }
    for u in unique_constraints {
        match u {
            UniqueConstraintChange::Removed(uc) => {
                emit_drop_constraint(out, qualified, &uc.name);
            }
            UniqueConstraintChange::Changed { target, .. } => {
                emit_drop_constraint(out, qualified, &target.name);
            }
            UniqueConstraintChange::Added(_) => {}
        }
    }
    for i in indexes {
        match i {
            IndexChange::Removed(idx) => emit_drop_index(out, qualified, &idx.name),
            IndexChange::Changed { target, .. } => emit_drop_index(out, qualified, &target.name),
            IndexChange::Added(_) => {}
        }
    }

    // Drop existing default constraints for columns whose default is
    // about to change. The synthesised name follows the same
    // convention as new defaults (see emit_default_constraint).
    for change in columns {
        if let ColumnChange::DefaultChanged { name, target, .. } = change {
            if target.is_some() {
                emit_drop_constraint(out, qualified, &default_constraint_name(table_name, name));
            }
        }
    }

    // Column phase: coalesce per-column type / nullable changes into
    // one ALTER COLUMN. Defaults are emitted separately via the
    // dedicated DEFAULT-constraint path below because T-SQL's
    // ALTER COLUMN cannot carry a DEFAULT clause.
    emit_column_changes_coalesced(out, table_name, qualified, columns);

    // After-the-alter: add the new default constraints for any
    // DefaultChanged whose source side is Some(...).
    for change in columns {
        if let ColumnChange::DefaultChanged {
            name,
            source: Some(expr),
            ..
        } = change
        {
            emit_default_constraint(out, table_name, qualified, name, expr);
        }
    }

    // Recreate phase: indexes → UNIQUE → FKs.
    for i in indexes {
        match i {
            IndexChange::Added(idx) | IndexChange::Changed { source: idx, .. } => {
                emit_create_index(out, qualified, idx);
            }
            IndexChange::Removed(_) => {}
        }
    }
    for u in unique_constraints {
        match u {
            UniqueConstraintChange::Added(uc)
            | UniqueConstraintChange::Changed { source: uc, .. } => {
                emit_add_unique(out, qualified, uc);
            }
            UniqueConstraintChange::Removed(_) => {}
        }
    }
    for f in foreign_keys {
        match f {
            ForeignKeyChange::Added(fk) | ForeignKeyChange::Changed { source: fk, .. } => {
                emit_add_fk(out, qualified, fk);
            }
            ForeignKeyChange::Removed(_) => {}
        }
    }
}

/// Coalesce per-column type / nullable changes into one ALTER
/// COLUMN statement. Added / Removed get their own statement. Default
/// changes are NOT handled here — see `emit_default_constraint`.
fn emit_column_changes_coalesced(
    out: &mut String,
    table_name: &str,
    qualified: &str,
    changes: &[ColumnChange],
) {
    #[derive(Default)]
    struct Pending {
        new_type: Option<String>,
        new_nullable: Option<bool>,
        touched: bool,
    }
    let mut per_column: BTreeMap<String, Pending> = BTreeMap::new();

    for change in changes {
        match change {
            ColumnChange::Added(c) => {
                out.push_str("ALTER TABLE ");
                out.push_str(qualified);
                out.push_str(" ADD ");
                emit_column_def(out, table_name, c);
                out.push_str(";\n");
            }
            ColumnChange::Removed(c) => {
                out.push_str("ALTER TABLE ");
                out.push_str(qualified);
                out.push_str(" DROP COLUMN ");
                out.push_str(&c.name);
                out.push_str(";\n");
            }
            ColumnChange::TypeChanged { name, source, .. } => {
                let p = per_column.entry(name.clone()).or_default();
                p.new_type = Some(source.clone());
                p.touched = true;
            }
            ColumnChange::NullableChanged { name, source, .. } => {
                let p = per_column.entry(name.clone()).or_default();
                p.new_nullable = Some(*source);
                p.touched = true;
            }
            // Defaults are handled outside this fn.
            ColumnChange::DefaultChanged { .. } => {}
        }
    }

    for (name, p) in per_column.iter().filter(|(_, p)| p.touched) {
        out.push_str("ALTER TABLE ");
        out.push_str(qualified);
        out.push_str(" ALTER COLUMN ");
        out.push_str(name);
        out.push(' ');
        if let Some(ty) = p.new_type.as_ref() {
            out.push_str(ty);
        } else {
            out.push_str("/* keep existing type */");
        }
        if let Some(nullable) = p.new_nullable {
            out.push_str(if nullable { " NULL" } else { " NOT NULL" });
        }
        out.push_str(";\n");
    }
}

fn emit_column_def(out: &mut String, table_name: &str, c: &Column) {
    out.push_str(&c.name);
    out.push(' ');
    out.push_str(&c.data_type);
    if !c.nullable {
        out.push_str(" NOT NULL");
    }
    if let Some(def) = c.default.as_ref() {
        // Inline defaults during a CREATE / ADD COLUMN: T-SQL accepts
        // the inline form here; the named constraint form is only
        // needed for ALTERs.
        out.push_str(" CONSTRAINT ");
        out.push_str(&default_constraint_name(table_name, &c.name));
        out.push_str(" DEFAULT ");
        out.push_str(def);
    }
    if c.primary_key {
        out.push_str(" PRIMARY KEY");
    }
}

fn emit_default_constraint(
    out: &mut String,
    table_name: &str,
    qualified: &str,
    column: &str,
    expr: &str,
) {
    out.push_str("ALTER TABLE ");
    out.push_str(qualified);
    out.push_str(" ADD CONSTRAINT ");
    out.push_str(&default_constraint_name(table_name, column));
    out.push_str(" DEFAULT ");
    out.push_str(expr);
    out.push_str(" FOR ");
    out.push_str(column);
    out.push_str(";\n");
}

/// Synthesise a stable default-constraint name. Operators who
/// already have a named convention can search-and-replace; the
/// header comment names the convention so the substitution is
/// obvious.
fn default_constraint_name(table: &str, column: &str) -> String {
    format!("df_{table}_{column}")
}

fn emit_create_index(out: &mut String, table: &str, idx: &Index) {
    out.push_str("CREATE ");
    if idx.unique {
        out.push_str("UNIQUE ");
    }
    out.push_str("INDEX ");
    out.push_str(&idx.name);
    out.push_str(" ON ");
    out.push_str(table);
    out.push_str(" (");
    out.push_str(&idx.columns.join(", "));
    out.push_str(");\n");
}

fn emit_drop_index(out: &mut String, table: &str, name: &str) {
    out.push_str("DROP INDEX ");
    out.push_str(name);
    out.push_str(" ON ");
    out.push_str(table);
    out.push_str(";\n");
}

fn emit_drop_constraint(out: &mut String, table: &str, name: &str) {
    out.push_str("ALTER TABLE ");
    out.push_str(table);
    out.push_str(" DROP CONSTRAINT ");
    out.push_str(name);
    out.push_str(";\n");
}

fn emit_add_fk(out: &mut String, table: &str, f: &ForeignKey) {
    out.push_str("ALTER TABLE ");
    out.push_str(table);
    out.push_str(" ADD CONSTRAINT ");
    out.push_str(&f.name);
    out.push_str(" FOREIGN KEY (");
    out.push_str(&f.columns.join(", "));
    out.push_str(") REFERENCES ");
    if let Some(s) = f.referenced_schema.as_deref() {
        out.push_str(s);
        out.push('.');
    }
    out.push_str(&f.referenced_table);
    out.push_str(" (");
    out.push_str(&f.referenced_columns.join(", "));
    out.push(')');
    if let Some(action) = f.on_update {
        out.push_str(" ON UPDATE ");
        out.push_str(action.as_sql());
    }
    if let Some(action) = f.on_delete {
        out.push_str(" ON DELETE ");
        out.push_str(action.as_sql());
    }
    out.push_str(";\n");
}

fn emit_add_unique(out: &mut String, table: &str, u: &UniqueConstraint) {
    out.push_str("ALTER TABLE ");
    out.push_str(table);
    out.push_str(" ADD CONSTRAINT ");
    out.push_str(&u.name);
    out.push_str(" UNIQUE (");
    out.push_str(&u.columns.join(", "));
    out.push_str(");\n");
}
