//! `MySQL` / `MariaDB` DDL emitter.
//!
//! Targets `MySQL` 8.0+ and recent `MariaDB` releases. Key differences
//! from Postgres:
//!
//! - Column modification uses `ALTER TABLE ... MODIFY COLUMN c <type>
//!   [NOT NULL] [DEFAULT ...]` — the column definition is rewritten
//!   as a whole rather than touched piecewise. Type, nullable, and
//!   default deltas on the same column are therefore coalesced into
//!   one statement instead of three.
//! - Constraints are dropped with `DROP FOREIGN KEY` (for FKs),
//!   `DROP INDEX` (for indexes), and `DROP CONSTRAINT` (for the
//!   modern UNIQUE form on 8.0.19+; `MariaDB` also accepts it).
//! - Indexes are scoped to a table: `DROP INDEX <name> ON <table>`.
//! - No `USING` clause — `MySQL` infers the cast and raises a
//!   warning when it can't.

use std::collections::BTreeMap;

use narwhal_core::schema::{Column, ForeignKey, Index, TableSchema, UniqueConstraint};

use super::{DdlEmitter, qualify};
use crate::SchemaDiffError;
use crate::diff::{
    ColumnChange, ForeignKeyChange, IndexChange, SchemaDiff, TableChange, UniqueConstraintChange,
};

/// `MySQL` / `MariaDB` DDL emitter. Stateless.
#[derive(Debug, Default, Clone, Copy)]
pub struct MysqlEmitter;

impl MysqlEmitter {
    /// Construct a fresh emitter. Zero-cost.
    #[must_use]
    pub const fn new() -> Self {
        Self
    }
}

impl DdlEmitter for MysqlEmitter {
    fn name(&self) -> &'static str {
        "mysql"
    }

    fn emit(&self, diff: &SchemaDiff) -> Result<String, SchemaDiffError> {
        let mut out = String::with_capacity(diff.change_count() * 160 + 64);
        out.push_str("-- generated by narwhal schema-diff (mysql dialect)\n");
        for change in &diff.tables {
            match change {
                TableChange::Added(t) => emit_create_table(&mut out, t),
                TableChange::Removed(t) => emit_drop_table(&mut out, t),
                TableChange::Changed {
                    table,
                    columns,
                    indexes,
                    foreign_keys,
                    unique_constraints,
                } => {
                    let qualified = qualify(&table.schema, &table.name);
                    emit_changed_table(
                        &mut out,
                        &qualified,
                        columns,
                        indexes,
                        foreign_keys,
                        unique_constraints,
                    );
                }
            }
            out.push('\n');
        }
        Ok(out)
    }
}

fn emit_create_table(out: &mut String, schema: &TableSchema) {
    out.push_str("CREATE TABLE ");
    out.push_str(&qualify(&schema.table.schema, &schema.table.name));
    out.push_str(" (\n");
    let total = schema.columns.len();
    for (i, c) in schema.columns.iter().enumerate() {
        out.push_str("    ");
        emit_column_def(out, c);
        if i + 1 < total {
            out.push(',');
        }
        out.push('\n');
    }
    out.push_str(");\n");
    let qualified = qualify(&schema.table.schema, &schema.table.name);
    for idx in &schema.indexes {
        if idx.primary {
            continue;
        }
        emit_create_index(out, &qualified, idx);
    }
    for u in &schema.unique_constraints {
        emit_add_unique(out, &qualified, u);
    }
    for f in &schema.foreign_keys {
        emit_add_fk(out, &qualified, f);
    }
}

fn emit_drop_table(out: &mut String, schema: &TableSchema) {
    out.push_str("DROP TABLE ");
    out.push_str(&qualify(&schema.table.schema, &schema.table.name));
    out.push_str(";\n");
}

fn emit_changed_table(
    out: &mut String,
    qualified: &str,
    columns: &[ColumnChange],
    indexes: &[IndexChange],
    foreign_keys: &[ForeignKeyChange],
    unique_constraints: &[UniqueConstraintChange],
) {
    // Drop phase: FKs first (engine refuses to drop a column under a
    // live FK), then UNIQUE, then indexes.
    for f in foreign_keys {
        match f {
            ForeignKeyChange::Removed(fk) => emit_drop_fk(out, qualified, &fk.name),
            ForeignKeyChange::Changed { target, .. } => emit_drop_fk(out, qualified, &target.name),
            ForeignKeyChange::Added(_) => {}
        }
    }
    for u in unique_constraints {
        match u {
            UniqueConstraintChange::Removed(uc) => {
                emit_drop_constraint(out, qualified, &uc.name);
            }
            UniqueConstraintChange::Changed { target, .. } => {
                emit_drop_constraint(out, qualified, &target.name);
            }
            UniqueConstraintChange::Added(_) => {}
        }
    }
    for i in indexes {
        match i {
            IndexChange::Removed(idx) => emit_drop_index(out, qualified, &idx.name),
            IndexChange::Changed { target, .. } => emit_drop_index(out, qualified, &target.name),
            IndexChange::Added(_) => {}
        }
    }

    // Column phase: coalesce all per-column deltas into one
    // MODIFY COLUMN statement. Added / Removed remain separate.
    emit_column_changes_coalesced(out, qualified, columns);

    // Recreate phase: indexes → UNIQUE → FKs.
    for i in indexes {
        match i {
            IndexChange::Added(idx) | IndexChange::Changed { source: idx, .. } => {
                emit_create_index(out, qualified, idx);
            }
            IndexChange::Removed(_) => {}
        }
    }
    for u in unique_constraints {
        match u {
            UniqueConstraintChange::Added(uc)
            | UniqueConstraintChange::Changed { source: uc, .. } => {
                emit_add_unique(out, qualified, uc);
            }
            UniqueConstraintChange::Removed(_) => {}
        }
    }
    for f in foreign_keys {
        match f {
            ForeignKeyChange::Added(fk) | ForeignKeyChange::Changed { source: fk, .. } => {
                emit_add_fk(out, qualified, fk);
            }
            ForeignKeyChange::Removed(_) => {}
        }
    }
}

/// Group column-level changes by column name. For columns that have
/// at least one type / nullable / default delta, emit a single
/// `MODIFY COLUMN` statement carrying the full new shape. `Added`
/// and `Removed` remain on their own statement each.
fn emit_column_changes_coalesced(out: &mut String, table: &str, changes: &[ColumnChange]) {
    // Per-column collector for the MODIFY path.
    #[derive(Default)]
    struct Pending {
        new_type: Option<String>,
        // `Some(b)` means the desired post-migration nullability.
        // `None` means "no change to nullability"; we still need a
        // value to emit, so it falls back to the existing one we
        // copy from the change record (see logic below).
        new_nullable: Option<bool>,
        // `Option<Option<String>>` carries three states: not seen
        // (`None`), drop the default (`Some(None)`), set to expr
        // (`Some(Some("..."))`). Clippy nags about the nested Option
        // but the third state is real — a custom enum would just add
        // noise.
        #[allow(clippy::option_option)]
        new_default: Option<Option<String>>,
        // True when at least one of the three deltas above was
        // captured for this column.
        touched: bool,
    }
    let mut per_column: BTreeMap<String, Pending> = BTreeMap::new();

    for change in changes {
        match change {
            ColumnChange::Added(c) => {
                out.push_str("ALTER TABLE ");
                out.push_str(table);
                out.push_str(" ADD COLUMN ");
                emit_column_def(out, c);
                out.push_str(";\n");
            }
            ColumnChange::Removed(c) => {
                out.push_str("ALTER TABLE ");
                out.push_str(table);
                out.push_str(" DROP COLUMN ");
                out.push_str(&c.name);
                out.push_str(";\n");
            }
            ColumnChange::TypeChanged { name, source, .. } => {
                let p = per_column.entry(name.clone()).or_default();
                p.new_type = Some(source.clone());
                p.touched = true;
            }
            ColumnChange::NullableChanged { name, source, .. } => {
                let p = per_column.entry(name.clone()).or_default();
                p.new_nullable = Some(*source);
                p.touched = true;
            }
            ColumnChange::DefaultChanged { name, source, .. } => {
                let p = per_column.entry(name.clone()).or_default();
                p.new_default = Some(source.clone());
                p.touched = true;
            }
        }
    }

    for (name, p) in per_column.iter().filter(|(_, p)| p.touched) {
        // MySQL MODIFY COLUMN needs the full new shape. The diff
        // doesn't carry the unchanged attributes alongside the delta,
        // so we render what we know and let the operator review.
        // M4.2: When no type delta exists we cannot emit a valid
        // MODIFY COLUMN (MySQL requires the type). Emit a TODO
        // comment instead so an incomplete statement never ships.
        let Some(ty) = p.new_type.as_ref() else {
            out.push_str("-- TODO: type required to MODIFY column '");
            out.push_str(name);
            out.push_str("' (nullable/default changed but type unknown)\n");
            continue;
        };
        out.push_str("ALTER TABLE ");
        out.push_str(table);
        out.push_str(" MODIFY COLUMN ");
        out.push_str(name);
        out.push(' ');
        out.push_str(ty);
        if let Some(nullable) = p.new_nullable {
            out.push_str(if nullable { " NULL" } else { " NOT NULL" });
        }
        if let Some(def) = p.new_default.as_ref() {
            match def {
                Some(expr) => {
                    out.push_str(" DEFAULT ");
                    out.push_str(expr);
                }
                None => {
                    // MODIFY COLUMN without an explicit DEFAULT
                    // drops the existing default. Mention it inline
                    // so a reader knows the omission is intentional.
                    out.push_str(" /* default dropped */");
                }
            }
        }
        out.push_str(";\n");
    }
}

fn emit_column_def(out: &mut String, c: &Column) {
    out.push_str(&c.name);
    out.push(' ');
    out.push_str(&c.data_type);
    if !c.nullable {
        out.push_str(" NOT NULL");
    }
    if let Some(def) = c.default.as_ref() {
        out.push_str(" DEFAULT ");
        out.push_str(def);
    }
    if c.primary_key {
        out.push_str(" PRIMARY KEY");
    }
}

fn emit_create_index(out: &mut String, table: &str, idx: &Index) {
    out.push_str("CREATE ");
    if idx.unique {
        out.push_str("UNIQUE ");
    }
    out.push_str("INDEX ");
    out.push_str(&idx.name);
    out.push_str(" ON ");
    out.push_str(table);
    out.push_str(" (");
    out.push_str(&idx.columns.join(", "));
    out.push_str(");\n");
}

fn emit_drop_index(out: &mut String, table: &str, name: &str) {
    // MySQL syntax mandates `ON <table>` because index names are
    // table-scoped, not schema-scoped.
    out.push_str("DROP INDEX ");
    out.push_str(name);
    out.push_str(" ON ");
    out.push_str(table);
    out.push_str(";\n");
}

fn emit_drop_fk(out: &mut String, table: &str, name: &str) {
    out.push_str("ALTER TABLE ");
    out.push_str(table);
    out.push_str(" DROP FOREIGN KEY ");
    out.push_str(name);
    out.push_str(";\n");
}

fn emit_drop_constraint(out: &mut String, table: &str, name: &str) {
    // UNIQUE constraints on MySQL 8.0.19+ are first-class — earlier
    // versions only exposed them through the underlying index. The
    // index emit path handles the fallback automatically when the
    // engine returned the constraint as an index instead.
    out.push_str("ALTER TABLE ");
    out.push_str(table);
    out.push_str(" DROP CONSTRAINT ");
    out.push_str(name);
    out.push_str(";\n");
}

fn emit_add_fk(out: &mut String, table: &str, f: &ForeignKey) {
    out.push_str("ALTER TABLE ");
    out.push_str(table);
    out.push_str(" ADD CONSTRAINT ");
    out.push_str(&f.name);
    out.push_str(" FOREIGN KEY (");
    out.push_str(&f.columns.join(", "));
    out.push_str(") REFERENCES ");
    if let Some(s) = f.referenced_schema.as_deref() {
        out.push_str(s);
        out.push('.');
    }
    out.push_str(&f.referenced_table);
    out.push_str(" (");
    out.push_str(&f.referenced_columns.join(", "));
    out.push(')');
    if let Some(action) = f.on_update {
        out.push_str(" ON UPDATE ");
        out.push_str(action.as_sql());
    }
    if let Some(action) = f.on_delete {
        out.push_str(" ON DELETE ");
        out.push_str(action.as_sql());
    }
    out.push_str(";\n");
}

fn emit_add_unique(out: &mut String, table: &str, u: &UniqueConstraint) {
    out.push_str("ALTER TABLE ");
    out.push_str(table);
    out.push_str(" ADD CONSTRAINT ");
    out.push_str(&u.name);
    out.push_str(" UNIQUE (");
    out.push_str(&u.columns.join(", "));
    out.push_str(");\n");
}

#[cfg(test)]
mod tests {
    use narwhal_core::schema::{Table, TableKind};

    use super::MysqlEmitter;
    use crate::diff::{ColumnChange, SchemaDiff, TableChange};
    use crate::emit::DdlEmitter;

    fn emitter() -> MysqlEmitter {
        MysqlEmitter::new()
    }

    fn table(name: &str) -> Table {
        Table {
            schema: "public".into(),
            name: name.into(),
            kind: TableKind::Table,
        }
    }

    fn schema_one_table(table_change: TableChange) -> SchemaDiff {
        SchemaDiff {
            tables: vec![table_change],
        }
    }

    #[test]
    fn mysql_modify_column_with_type_emits_valid_sql() {
        // When type is present, MODIFY COLUMN is well-formed.
        let diff = schema_one_table(TableChange::Changed {
            table: table("users"),
            columns: vec![ColumnChange::TypeChanged {
                name: "id".into(),
                source: "BIGINT".into(),
                target: "INT".into(),
            }],
            indexes: vec![],
            foreign_keys: vec![],
            unique_constraints: vec![],
        });
        let sql = emitter().emit(&diff).unwrap();
        assert!(sql.contains("MODIFY COLUMN id BIGINT"), "got: {sql}");
        assert!(!sql.contains("/*"), "no inline comments: {sql}");
    }

    #[test]
    fn mysql_modify_column_without_type_emits_todo_comment() {
        // M4.2: When only nullable/default changed (no type delta),
        // we cannot emit a valid MODIFY COLUMN without the type.
        // The old code put `/* keep existing type */` inline which
        // produces invalid SQL. Now it emits a TODO comment instead.
        let diff = schema_one_table(TableChange::Changed {
            table: table("users"),
            columns: vec![ColumnChange::NullableChanged {
                name: "name".into(),
                source: false,
                target: true,
            }],
            indexes: vec![],
            foreign_keys: vec![],
            unique_constraints: vec![],
        });
        let sql = emitter().emit(&diff).unwrap();
        // Must NOT contain invalid SQL with inline comment.
        assert!(!sql.contains("/*"), "inline comment is invalid SQL: {sql}");
        // Must NOT contain MODIFY COLUMN without a real type.
        assert!(
            !sql.contains("MODIFY COLUMN"),
            "MODIFY COLUMN without type is invalid: {sql}"
        );
        // Must contain a TODO comment noting the missing type.
        assert!(
            sql.contains("-- TODO: type required to MODIFY column 'name'"),
            "expected TODO comment, got: {sql}"
        );
    }

    #[test]
    fn mysql_modify_column_without_type_but_with_default_emits_todo() {
        let diff = schema_one_table(TableChange::Changed {
            table: table("orders"),
            columns: vec![ColumnChange::DefaultChanged {
                name: "status".into(),
                source: Some("'pending'".into()),
                target: None,
            }],
            indexes: vec![],
            foreign_keys: vec![],
            unique_constraints: vec![],
        });
        let sql = emitter().emit(&diff).unwrap();
        assert!(!sql.contains("/*"), "no inline comments: {sql}");
        assert!(
            !sql.contains("MODIFY COLUMN"),
            "no MODIFY COLUMN without type: {sql}"
        );
        assert!(
            sql.contains("-- TODO: type required to MODIFY column 'status'"),
            "expected TODO comment, got: {sql}"
        );
    }
}
