//! `PostgreSQL` DDL emitter.
//!
//! Targets Postgres 12+. Key differences from the generic / ANSI
//! fallback:
//!
//! - Type changes use `ALTER COLUMN ... TYPE ... USING <col>::<type>`
//!   so the engine has an explicit cast hint. The cast is a
//!   best-effort default; non-trivial conversions (e.g. text → jsonb)
//!   will still need a hand-written `USING` expression, but the
//!   emitted form runs cleanly for the common widening / narrowing
//!   cases.
//! - Defaults are altered with `ALTER COLUMN ... SET/DROP DEFAULT`.
//! - Nullability with `ALTER COLUMN ... SET/DROP NOT NULL`.
//! - Constraints are dropped before column work and recreated after,
//!   so a column type change cannot trip a referencing FK during the
//!   middle of the migration.
//!
//! Identifier quoting is *not* applied — narwhal stores
//! introspection results as the engine reports them and we round-
//! trip the same casing. A future step can wire in `"` quoting if
//! mixed-case identifiers become a target audience.

use narwhal_core::schema::{Column, ForeignKey, Index, TableSchema, UniqueConstraint};

use super::{DdlEmitter, qualify};
use crate::SchemaDiffError;
use crate::diff::{
    ColumnChange, ForeignKeyChange, IndexChange, SchemaDiff, TableChange, UniqueConstraintChange,
};

/// `PostgreSQL` DDL emitter. Stateless.
#[derive(Debug, Default, Clone, Copy)]
pub struct PostgresEmitter;

impl PostgresEmitter {
    /// Construct a fresh emitter. Zero-cost.
    #[must_use]
    pub const fn new() -> Self {
        Self
    }
}

impl DdlEmitter for PostgresEmitter {
    fn name(&self) -> &'static str {
        "postgres"
    }

    fn emit(&self, diff: &SchemaDiff) -> Result<String, SchemaDiffError> {
        let mut out = String::with_capacity(diff.change_count() * 160 + 64);
        out.push_str("-- generated by narwhal schema-diff (postgres dialect)\n");
        for change in &diff.tables {
            match change {
                TableChange::Added(t) => emit_create_table(&mut out, t),
                TableChange::Removed(t) => emit_drop_table(&mut out, t),
                TableChange::Changed {
                    table,
                    columns,
                    indexes,
                    foreign_keys,
                    unique_constraints,
                } => {
                    let qualified = qualify(&table.schema, &table.name);
                    emit_changed_table(
                        &mut out,
                        &table.schema,
                        &qualified,
                        columns,
                        indexes,
                        foreign_keys,
                        unique_constraints,
                    );
                }
            }
            out.push('\n');
        }
        Ok(out)
    }
}

fn emit_create_table(out: &mut String, schema: &TableSchema) {
    out.push_str("CREATE TABLE ");
    out.push_str(&qualify(&schema.table.schema, &schema.table.name));
    out.push_str(" (\n");
    let total = schema.columns.len();
    for (i, c) in schema.columns.iter().enumerate() {
        out.push_str("    ");
        emit_column_def(out, c);
        if i + 1 < total {
            out.push(',');
        }
        out.push('\n');
    }
    out.push_str(");\n");
    for idx in &schema.indexes {
        if idx.primary {
            continue;
        }
        emit_create_index(out, &schema.table.schema, &schema.table.name, idx);
    }
    for u in &schema.unique_constraints {
        emit_add_unique(out, &qualify(&schema.table.schema, &schema.table.name), u);
    }
    for f in &schema.foreign_keys {
        emit_add_fk(out, &qualify(&schema.table.schema, &schema.table.name), f);
    }
}

fn emit_drop_table(out: &mut String, schema: &TableSchema) {
    out.push_str("DROP TABLE ");
    out.push_str(&qualify(&schema.table.schema, &schema.table.name));
    out.push_str(";\n");
}

fn emit_changed_table(
    out: &mut String,
    schema_name: &str,
    qualified: &str,
    columns: &[ColumnChange],
    indexes: &[IndexChange],
    foreign_keys: &[ForeignKeyChange],
    unique_constraints: &[UniqueConstraintChange],
) {
    // Phase 1: drop. Constraints referencing soon-to-change columns
    // would otherwise block an ALTER COLUMN TYPE.
    for f in foreign_keys {
        match f {
            ForeignKeyChange::Removed(fk) => emit_drop_fk(out, qualified, &fk.name),
            ForeignKeyChange::Changed { target, .. } => emit_drop_fk(out, qualified, &target.name),
            ForeignKeyChange::Added(_) => {}
        }
    }
    for u in unique_constraints {
        match u {
            UniqueConstraintChange::Removed(uc) => {
                emit_drop_constraint(out, qualified, &uc.name);
            }
            UniqueConstraintChange::Changed { target, .. } => {
                emit_drop_constraint(out, qualified, &target.name);
            }
            UniqueConstraintChange::Added(_) => {}
        }
    }
    for i in indexes {
        match i {
            IndexChange::Removed(idx) => emit_drop_index(out, schema_name, &idx.name),
            IndexChange::Changed { target, .. } => emit_drop_index(out, schema_name, &target.name),
            IndexChange::Added(_) => {}
        }
    }

    // Phase 2: column-level changes.
    for c in columns {
        emit_column_change(out, qualified, c);
    }

    // Phase 3: recreate. Indexes first so constraints that lean on
    // them (e.g. UNIQUE backed by a unique index) see the index
    // already in place.
    for i in indexes {
        match i {
            IndexChange::Added(idx) | IndexChange::Changed { source: idx, .. } => {
                let table_name = qualified.rsplit('.').next().unwrap_or(qualified);
                emit_create_index(out, schema_name, table_name, idx);
            }
            IndexChange::Removed(_) => {}
        }
    }
    for u in unique_constraints {
        match u {
            UniqueConstraintChange::Added(uc)
            | UniqueConstraintChange::Changed { source: uc, .. } => {
                emit_add_unique(out, qualified, uc);
            }
            UniqueConstraintChange::Removed(_) => {}
        }
    }
    for f in foreign_keys {
        match f {
            ForeignKeyChange::Added(fk) | ForeignKeyChange::Changed { source: fk, .. } => {
                emit_add_fk(out, qualified, fk);
            }
            ForeignKeyChange::Removed(_) => {}
        }
    }
}

fn emit_column_def(out: &mut String, c: &Column) {
    out.push_str(&c.name);
    out.push(' ');
    out.push_str(&c.data_type);
    if !c.nullable {
        out.push_str(" NOT NULL");
    }
    if let Some(def) = c.default.as_ref() {
        out.push_str(" DEFAULT ");
        out.push_str(def);
    }
    if c.primary_key {
        out.push_str(" PRIMARY KEY");
    }
}

fn emit_column_change(out: &mut String, table: &str, change: &ColumnChange) {
    match change {
        ColumnChange::Added(c) => {
            out.push_str("ALTER TABLE ");
            out.push_str(table);
            out.push_str(" ADD COLUMN ");
            emit_column_def(out, c);
            out.push_str(";\n");
        }
        ColumnChange::Removed(c) => {
            out.push_str("ALTER TABLE ");
            out.push_str(table);
            out.push_str(" DROP COLUMN ");
            out.push_str(&c.name);
            out.push_str(";\n");
        }
        ColumnChange::TypeChanged { name, source, .. } => {
            // Default USING clause: cast the existing value through
            // the new type. Works for widening conversions and most
            // string ↔ numeric casts; the operator overrides for
            // anything richer.
            out.push_str("ALTER TABLE ");
            out.push_str(table);
            out.push_str(" ALTER COLUMN ");
            out.push_str(name);
            out.push_str(" TYPE ");
            out.push_str(source);
            out.push_str(" USING ");
            out.push_str(name);
            out.push_str("::");
            out.push_str(source);
            out.push_str(";\n");
        }
        ColumnChange::NullableChanged { name, source, .. } => {
            out.push_str("ALTER TABLE ");
            out.push_str(table);
            out.push_str(" ALTER COLUMN ");
            out.push_str(name);
            out.push_str(if *source {
                " DROP NOT NULL"
            } else {
                " SET NOT NULL"
            });
            out.push_str(";\n");
        }
        ColumnChange::DefaultChanged { name, source, .. } => {
            out.push_str("ALTER TABLE ");
            out.push_str(table);
            out.push_str(" ALTER COLUMN ");
            out.push_str(name);
            match source {
                Some(def) => {
                    out.push_str(" SET DEFAULT ");
                    out.push_str(def);
                }
                None => out.push_str(" DROP DEFAULT"),
            }
            out.push_str(";\n");
        }
    }
}

fn emit_create_index(out: &mut String, schema_name: &str, table_name: &str, idx: &Index) {
    out.push_str("CREATE ");
    if idx.unique {
        out.push_str("UNIQUE ");
    }
    out.push_str("INDEX ");
    out.push_str(&idx.name);
    out.push_str(" ON ");
    out.push_str(&qualify(schema_name, table_name));
    out.push_str(" (");
    out.push_str(&idx.columns.join(", "));
    out.push_str(");\n");
}

fn emit_drop_index(out: &mut String, schema_name: &str, index_name: &str) {
    // Postgres indexes are schema-qualified; if we know the schema
    // we render it, otherwise the search_path resolves the name.
    out.push_str("DROP INDEX ");
    out.push_str(&qualify(schema_name, index_name));
    out.push_str(";\n");
}

fn emit_drop_fk(out: &mut String, table: &str, name: &str) {
    out.push_str("ALTER TABLE ");
    out.push_str(table);
    out.push_str(" DROP CONSTRAINT ");
    out.push_str(name);
    out.push_str(";\n");
}

fn emit_drop_constraint(out: &mut String, table: &str, name: &str) {
    out.push_str("ALTER TABLE ");
    out.push_str(table);
    out.push_str(" DROP CONSTRAINT ");
    out.push_str(name);
    out.push_str(";\n");
}

fn emit_add_fk(out: &mut String, table: &str, f: &ForeignKey) {
    out.push_str("ALTER TABLE ");
    out.push_str(table);
    out.push_str(" ADD CONSTRAINT ");
    out.push_str(&f.name);
    out.push_str(" FOREIGN KEY (");
    out.push_str(&f.columns.join(", "));
    out.push_str(") REFERENCES ");
    if let Some(s) = f.referenced_schema.as_deref() {
        out.push_str(s);
        out.push('.');
    }
    out.push_str(&f.referenced_table);
    out.push_str(" (");
    out.push_str(&f.referenced_columns.join(", "));
    out.push(')');
    if let Some(action) = f.on_update {
        out.push_str(" ON UPDATE ");
        out.push_str(action.as_sql());
    }
    if let Some(action) = f.on_delete {
        out.push_str(" ON DELETE ");
        out.push_str(action.as_sql());
    }
    out.push_str(";\n");
}

fn emit_add_unique(out: &mut String, table: &str, u: &UniqueConstraint) {
    out.push_str("ALTER TABLE ");
    out.push_str(table);
    out.push_str(" ADD CONSTRAINT ");
    out.push_str(&u.name);
    out.push_str(" UNIQUE (");
    out.push_str(&u.columns.join(", "));
    out.push_str(");\n");
}
