//! `SQLite` DDL emitter.
//!
//! `SQLite`'s `ALTER TABLE` is famously narrow:
//!
//! | operation | supported since |
//! |---|---|
//! | `ADD COLUMN` | 3.2.0 (2005) |
//! | `RENAME COLUMN` | 3.25.0 (2018) |
//! | `RENAME TABLE` | 3.0.0 (2004) |
//! | `DROP COLUMN` | 3.35.0 (2021) |
//! | `ALTER COLUMN TYPE` | **never** |
//! | `ALTER COLUMN NULL` / `DEFAULT` | **never** |
//!
//! The emitter therefore renders what `SQLite` can express natively
//! and falls back to a comment block for anything that requires the
//! `CREATE NEW → INSERT SELECT → DROP OLD → RENAME` rebuild dance.
//! We deliberately do *not* attempt to auto-generate the rebuild
//! script: it needs the exact original schema (which we have) and
//! the original *data preservation* policy (which we don't), and a
//! silent rebuild that loses a column default would be worse than
//! the comment.
//!
//! Indexes and FKs are first-class in `SQLite`; index DROP / CREATE
//! works as expected, and FK definitions are part of the table
//! create so they ride along with rebuilds.

use narwhal_core::schema::{Column, Index, TableSchema};

use super::{DdlEmitter, qualify};
use crate::SchemaDiffError;
use crate::diff::{
    ColumnChange, ForeignKeyChange, IndexChange, SchemaDiff, TableChange, UniqueConstraintChange,
};

/// `SQLite` DDL emitter. Stateless.
#[derive(Debug, Default, Clone, Copy)]
pub struct SqliteEmitter;

impl SqliteEmitter {
    /// Construct a fresh emitter. Zero-cost.
    #[must_use]
    pub const fn new() -> Self {
        Self
    }
}

impl DdlEmitter for SqliteEmitter {
    fn name(&self) -> &'static str {
        "sqlite"
    }

    fn emit(&self, diff: &SchemaDiff) -> Result<String, SchemaDiffError> {
        let mut out = String::with_capacity(diff.change_count() * 160 + 128);
        out.push_str("-- generated by narwhal schema-diff (sqlite dialect)\n");
        out.push_str(
            "-- note: SQLite does not support ALTER COLUMN TYPE / NULL / DEFAULT.\n\
             --       Those changes are emitted as comments; perform them via the\n\
             --       create-new / copy / drop-old / rename rebuild idiom.\n",
        );
        for change in &diff.tables {
            match change {
                TableChange::Added(t) => emit_create_table(&mut out, t),
                TableChange::Removed(t) => emit_drop_table(&mut out, t),
                TableChange::Changed {
                    table,
                    columns,
                    indexes,
                    foreign_keys,
                    unique_constraints,
                } => {
                    let qualified = qualify(&table.schema, &table.name);
                    emit_changed_table(
                        &mut out,
                        &qualified,
                        columns,
                        indexes,
                        foreign_keys,
                        unique_constraints,
                    );
                }
            }
            out.push('\n');
        }
        Ok(out)
    }
}

fn emit_create_table(out: &mut String, schema: &TableSchema) {
    out.push_str("CREATE TABLE ");
    out.push_str(&qualify(&schema.table.schema, &schema.table.name));
    out.push_str(" (\n");
    let column_count = schema.columns.len();
    let fk_count = schema.foreign_keys.len();
    let unique_count = schema.unique_constraints.len();
    for (i, c) in schema.columns.iter().enumerate() {
        out.push_str("    ");
        emit_column_def(out, c);
        if i + 1 < column_count || fk_count > 0 || unique_count > 0 {
            out.push(',');
        }
        out.push('\n');
    }
    // SQLite supports table-level constraints inline. Pulling them
    // into the CREATE means the rebuild path can use this single
    // emit fn as its template.
    for (i, u) in schema.unique_constraints.iter().enumerate() {
        out.push_str("    UNIQUE (");
        out.push_str(&u.columns.join(", "));
        out.push(')');
        let more = i + 1 < unique_count || fk_count > 0;
        if more {
            out.push(',');
        }
        out.push('\n');
    }
    for (i, f) in schema.foreign_keys.iter().enumerate() {
        out.push_str("    FOREIGN KEY (");
        out.push_str(&f.columns.join(", "));
        out.push_str(") REFERENCES ");
        if let Some(s) = f.referenced_schema.as_deref() {
            out.push_str(s);
            out.push('.');
        }
        out.push_str(&f.referenced_table);
        out.push_str(" (");
        out.push_str(&f.referenced_columns.join(", "));
        out.push(')');
        if let Some(action) = f.on_update {
            out.push_str(" ON UPDATE ");
            out.push_str(action.as_sql());
        }
        if let Some(action) = f.on_delete {
            out.push_str(" ON DELETE ");
            out.push_str(action.as_sql());
        }
        if i + 1 < fk_count {
            out.push(',');
        }
        out.push('\n');
    }
    out.push_str(");\n");
    for idx in &schema.indexes {
        if idx.primary {
            continue;
        }
        emit_create_index(out, &qualify(&schema.table.schema, &schema.table.name), idx);
    }
}

fn emit_drop_table(out: &mut String, schema: &TableSchema) {
    out.push_str("DROP TABLE ");
    out.push_str(&qualify(&schema.table.schema, &schema.table.name));
    out.push_str(";\n");
}

fn emit_changed_table(
    out: &mut String,
    qualified: &str,
    columns: &[ColumnChange],
    indexes: &[IndexChange],
    foreign_keys: &[ForeignKeyChange],
    unique_constraints: &[UniqueConstraintChange],
) {
    // SQLite has no DROP CONSTRAINT for FK / UNIQUE. They live inside
    // the table definition; mutating them requires the rebuild
    // idiom. We surface every FK / UNIQUE delta as a comment so the
    // operator sees the intent.
    for f in foreign_keys {
        match f {
            ForeignKeyChange::Added(fk) => {
                push_comment(
                    out,
                    &format!(
                        "table rebuild needed: add FK {name} on {qualified} ({cols}) → {ref_table} ({ref_cols})",
                        name = fk.name,
                        cols = fk.columns.join(", "),
                        ref_table = fk.referenced_table,
                        ref_cols = fk.referenced_columns.join(", "),
                    ),
                );
            }
            ForeignKeyChange::Removed(fk) => {
                push_comment(
                    out,
                    &format!(
                        "table rebuild needed: drop FK {name} on {qualified}",
                        name = fk.name,
                    ),
                );
            }
            ForeignKeyChange::Changed { source, .. } => {
                push_comment(
                    out,
                    &format!(
                        "table rebuild needed: change FK {name} on {qualified}",
                        name = source.name,
                    ),
                );
            }
        }
    }
    for u in unique_constraints {
        match u {
            UniqueConstraintChange::Added(uc) => push_comment(
                out,
                &format!(
                    "table rebuild needed: add UNIQUE {name} on {qualified} ({cols})",
                    name = uc.name,
                    cols = uc.columns.join(", "),
                ),
            ),
            UniqueConstraintChange::Removed(uc) => push_comment(
                out,
                &format!(
                    "table rebuild needed: drop UNIQUE {name} on {qualified}",
                    name = uc.name,
                ),
            ),
            UniqueConstraintChange::Changed { source, .. } => push_comment(
                out,
                &format!(
                    "table rebuild needed: change UNIQUE {name} on {qualified}",
                    name = source.name,
                ),
            ),
        }
    }

    // Columns: ADD and DROP work natively; the rest needs a rebuild.
    for c in columns {
        emit_column_change(out, qualified, c);
    }

    // Indexes are first-class: drop / create away.
    for i in indexes {
        match i {
            IndexChange::Added(idx) => emit_create_index(out, qualified, idx),
            IndexChange::Removed(idx) => emit_drop_index(out, &idx.name),
            IndexChange::Changed { source, target } => {
                emit_drop_index(out, &target.name);
                emit_create_index(out, qualified, source);
            }
        }
    }
}

fn emit_column_change(out: &mut String, table: &str, change: &ColumnChange) {
    match change {
        ColumnChange::Added(c) => {
            out.push_str("ALTER TABLE ");
            out.push_str(table);
            out.push_str(" ADD COLUMN ");
            emit_column_def(out, c);
            out.push_str(";\n");
        }
        ColumnChange::Removed(c) => {
            // DROP COLUMN requires SQLite 3.35+ (2021). Older
            // databases need the rebuild idiom. We emit the modern
            // form and let the operator check the engine version.
            out.push_str("ALTER TABLE ");
            out.push_str(table);
            out.push_str(" DROP COLUMN ");
            out.push_str(&c.name);
            out.push_str(";  -- requires SQLite >= 3.35\n");
        }
        ColumnChange::TypeChanged {
            name,
            source,
            target,
        } => {
            push_comment(
                out,
                &format!(
                    "table rebuild needed: change type of {table}.{name} from {target} to {source}",
                ),
            );
        }
        ColumnChange::NullableChanged { name, source, .. } => {
            push_comment(
                out,
                &format!(
                    "table rebuild needed: set {table}.{name} {} NULL",
                    if *source { "" } else { "NOT" },
                ),
            );
        }
        ColumnChange::DefaultChanged { name, source, .. } => {
            push_comment(
                out,
                &format!(
                    "table rebuild needed: alter default on {table}.{name} (desired: {source:?})",
                ),
            );
        }
    }
}

fn emit_column_def(out: &mut String, c: &Column) {
    out.push_str(&c.name);
    out.push(' ');
    out.push_str(&c.data_type);
    if !c.nullable {
        out.push_str(" NOT NULL");
    }
    if let Some(def) = c.default.as_ref() {
        out.push_str(" DEFAULT ");
        out.push_str(def);
    }
    if c.primary_key {
        out.push_str(" PRIMARY KEY");
    }
}

fn emit_create_index(out: &mut String, table: &str, idx: &Index) {
    out.push_str("CREATE ");
    if idx.unique {
        out.push_str("UNIQUE ");
    }
    out.push_str("INDEX ");
    out.push_str(&idx.name);
    out.push_str(" ON ");
    out.push_str(table);
    out.push_str(" (");
    out.push_str(&idx.columns.join(", "));
    out.push_str(");\n");
}

fn emit_drop_index(out: &mut String, name: &str) {
    out.push_str("DROP INDEX ");
    out.push_str(name);
    out.push_str(";\n");
}

fn push_comment(out: &mut String, body: &str) {
    out.push_str("-- ");
    out.push_str(body);
    out.push('\n');
}
